### ISSUE TITLE
A new release is required to software supply chain safety warnings

### ISSUE THREAD

**Issue by cclauss** [facebook/pyre-action#7]
Fixes software supply chain safety warnings like on the bottom right of
https://github.com/cclauss/Personal-Digital-Assistant/actions/runs/8520371449

As discussed in
* #5
* #6

**Comment by arthaud** [comment]
What do you mean by "a new release is required"? From what I see, we don't provide a version number for the action. Should we start doing that?

**Comment by cclauss** [comment]
Something higher than `v0.0.1` at https://github.com/facebook/pyre-action/releases

See the commented line in https://github.com/facebook/pyre-action?tab=readme-ov-file#usage

**Comment by arthaud** [comment]
Done.
